EMBEDDING_DIMENSIONS = 128
HIDDEN_FEED_FORWARD_DIMENSIONS = EMBEDDING_DIMENSIONS * 4
TRANSFORMER_BLOCKS = 2

MAX_LENGTH = 4096
LEARNING_RATE = 0.01
EPOCH_COUNT = 100
SAVE_ON_EPOCH = 5  # save every 5 epochs

TOTAL_DATASET_ELEMENTS = 5000

RANDOM_SEED = 17
