EMBEDDING_DIMENSIONS = 128
HIDDEN_FEED_FORWARD_DIMENSIONS = EMBEDDING_DIMENSIONS * 4
TRANSFORMER_BLOCKS = 4

MAX_LENGTH = 3000
LEARNING_RATE = 0.001
EPOCH_COUNT = 1
SAVE_ON_EPOCH = 1  # save every epoch
DISPLAY_STEP_SIZE = 500

TOTAL_DATASET_ELEMENTS = 100_000

RANDOM_SEED = 17

TEMPERATURE = 0.7
SIMILARITY_WEIGHT = 0.8